# Generated by Django 6.0 on 2026-01-08 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_no', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=100, unique=True)),
                ('loc', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SALGRADE',
            fields=[
                ('grade', models.IntegerField(primary_key=True, serialize=False)),
                ('losal', models.IntegerField(null=True)),
                ('hisal', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EMP',
            fields=[
                ('emp_no', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('mgr', models.IntegerField(null=True)),
                ('hire_date', models.DateField(null=True)),
                ('sal', models.IntegerField(null=True)),
                ('comm', models.IntegerField()),
                ('dept_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
