# Generated by Django 6.0 on 2026-01-21 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_emp_comm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='mgr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.emp'),
        ),
    ]
