# Generated by Django 6.0 on 2026-01-08 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='accessrecord',
            name='author',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='accessrecord',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='accessrecord',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.webpage'),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
