# Generated by Django 6.0 on 2026-02-13 12:03

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, validators=[app.models.check_for_A]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('[6-9]\\d{9}'), django.core.validators.MinLengthValidator(10)]),
        ),
    ]
